'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PKMG5DC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a // Pokémon Duodecuple Distribution
        '''// by Prof. 9
        '''// Version 1.4.1 &quot;Skinless&quot;
        '''// 
        '''// Thanks to Yellow Wood Goblin for the slot-1 read fix.
        '''
        '''.include options.asm
        '''
        '''.nds
        '''.open arm7.bin,2380000h
        '''
        '''.org	23A6370h
        '''loadhijack:
        '''	push	r5,r14
        '''	bl	2007F98h
        '''	ldr	r0,=2013900h
        '''	ldr	r1,=2030000h
        '''	ldrb	r1,[r1]
        '''	mov	r1,r1,lsl 3h
        '''	ldr	r2,[r0,r1]
        '''	ldr	r1,=2011628h
        '''	ldr	r3,=16D0h
        '''	bl	2003874h
        '''
        '''	mov	r5,0h
        '''fixchecksum:
        '''	mov	r2,2D0h
        '''	mul	r2,r5
        '''	ldr	r1,=201162Ch
        '''	add	r1,r1,r2
        '''	ldr	r2,=2CEh
        '''	ldr	r0,=27E3 [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property _12distroasm() As String
            Get
                Return ResourceManager.GetString("_12distroasm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a 2020/7/25.
        '''</summary>
        Friend ReadOnly Property _date() As String
            Get
                Return ResourceManager.GetString("_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property armips() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("armips", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property ndstool() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ndstool", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Consulta uma cadeia de caracteres localizada semelhante a // amount of wonder cards (1-12)
        '''.definelabel amount,1
        '''
        '''// distance between names (pixels)
        '''.definelabel dist,12
        '''
        '''// status text color
        '''.definelabel test,0x7FFF
        '''
        '''// menu text color
        '''.definelabel menu,0x7FFF
        '''
        '''// selected text color
        '''.definelabel select,0x001F
        '''
        '''// text mode: 0=left, 1=center, 2=right
        '''.definelabel mode,1
        '''
        '''// menu text x-position (pixels)
        '''.definelabel mxpos,128
        '''
        '''// menu text y-position (pixels)
        '''.definelabel mypos,0
        '''
        '''// x-position for status text 1 (pixels)
        '''.definelabel d1xpos,128
        '''
        '''// y-position for [o restante da cadeia de caracteres foi truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property optionsasm() As String
            Get
                Return ResourceManager.GetString("optionsasm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ppdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ppdbs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppdbs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
