'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Gen5_Distribution_Creator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // Pokémon Duodecuple Distribution
        '''// by Prof. 9
        '''// Version 1.4.1 &quot;Skinless&quot;
        '''// With Edits by Regnum for PKMG5DC
        '''// Thanks to Yellow Wood Goblin for the slot-1 read fix.
        '''
        '''.include options.asm
        '''
        '''.nds
        '''.open arm7.bin,2380000h
        '''
        '''.org	23A6370h
        '''loadhijack:
        '''	push	r5,r14
        '''	bl	2007F98h
        '''	ldr	r0,=2013900h
        '''	ldr	r1,=2030000h
        '''	ldrb	r1,[r1]
        '''	mov	r1,r1,lsl 3h
        '''	ldr	r2,[r0,r1]
        '''	ldr	r1,=2011628h
        '''	ldr	r3,=16D0h
        '''	bl	2003874h
        '''
        '''	mov	r5,0h
        '''fixchecksum:
        '''	mov	r2,2D0h
        '''	mul	r2,r5
        '''	ldr	r1,=201162Ch
        '''	add	r1,r1, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _12distro() As String
            Get
                Return ResourceManager.GetString("_12distro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // Pokémon Duodecuple Distribution
        '''// by Prof. 9
        '''// Version 1.4.1 &quot;Skinless&quot;
        '''// With Edits by Regnum for PKMG5DC
        '''// Thanks to Yellow Wood Goblin for the slot-1 read fix.
        '''
        '''.include options.asm
        '''
        '''.nds
        '''.open arm7.bin,2380000h
        '''
        '''.org	23A6370h
        '''loadhijack:
        '''	push	r5,r14
        '''	bl	2007F98h
        '''	ldr	r0,=2013900h
        '''	ldr	r1,=2030000h
        '''	ldrb	r1,[r1]
        '''	mov	r1,r1,lsl 3h
        '''	ldr	r2,[r0,r1]
        '''	ldr	r1,=2011628h
        '''	ldr	r3,=16D0h
        '''	bl	2003874h
        '''
        '''	mov	r5,0h
        '''fixchecksum:
        '''	mov	r2,2D0h
        '''	mul	r2,r5
        '''	ldr	r1,=201162Ch
        '''	add	r1,r1, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _12distro_() As String
            Get
                Return ResourceManager.GetString("_12distro_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to :menu
        '''@echo off
        '''cls
        '''echo Pokemon Duodecuple Distribution v1.4.1 &quot;Skinless&quot;
        '''echo -------------------------------------------------
        '''echo 1. Create a 12-distro ROM
        '''echo 2. Extract Wonder Cards from a ROM
        '''echo 3. Compile Wonder Cards into a ROM
        '''echo 4. Exit
        '''echo -------------------------------------------------
        '''set choice=
        '''set /p choice=?
        '''if &quot;%choice%&quot;==&quot;1&quot; goto patch
        '''if &quot;%choice%&quot;==&quot;2&quot; goto extract
        '''if &quot;%choice%&quot;==&quot;3&quot; goto compile
        '''if &quot;%choice%&quot;==&quot;4&quot; exit
        '''goto menu
        '''
        ''':patch
        '''@echo off
        '''if not ex [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _12distro1() As String
            Get
                Return ResourceManager.GetString("_12distro1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2018/11/25.
        '''</summary>
        Friend ReadOnly Property _date() As String
            Get
                Return ResourceManager.GetString("_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property armips() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("armips", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ARMIPS assembler v0.7d, released April 1 2013
        '''by Kingcom
        '''http://aerie.wingdreams.net/
        '''
        '''#################################
        '''# 0.   TABLE OF CONTENTS        #
        '''#################################
        '''
        '''  1.   Introduction
        '''   1.1 Motivation
        '''   1.2 Usage
        '''   1.3 Change log
        '''  2.   General Information
        '''  3.   Features
        '''   3.1 Files
        '''   3.2 Comments
        '''   3.3 Labels
        '''   3.4 equ
        '''   3.5 Math Parser
        '''   3.6 Load delay detection
        '''   3.7 Strings
        '''   3.8 Areas
        '''  4.   Assembler Directives
        '''   4.1 General Directives
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property armips_readme() As String
            Get
                Return ResourceManager.GetString("armips_readme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;New Update Available! &quot;: &quot;New Update Available! &quot;,
        '''  &quot;Open .pgf&quot;: &quot;Open .pgf&quot;,
        '''  &quot;Custom&quot;: &quot;Custom&quot;,
        '''  &quot;Game Compatibility&quot;: &quot;Game Compatibility&quot;,
        '''  &quot;Black&quot;: &quot;Black&quot;,
        '''  &quot;White&quot;: &quot;White&quot;,
        '''  &quot;Date Limit&quot;: &quot;Date Limit&quot;,
        '''  &quot;Start&quot;: &quot;Start&quot;,
        '''  &quot;End&quot;: &quot;End&quot;,
        '''  &quot;Auto Max Limit&quot;: &quot;Auto Max Limit&quot;,
        '''  &quot;Region&quot;: &quot;Region&quot;,
        '''  &quot;ROM Details&quot;: &quot;ROM Details&quot;,
        '''  &quot;File Name&quot;: &quot;File Name&quot;,
        '''  &quot;Header&quot;: &quot;Header&quot;,
        '''  &quot;Code&quot;: &quot;Code&quot;,
        '''  &quot;Description&quot;: &quot;Description&quot;,
        '''  &quot;Clear Text&quot;: &quot;Clear Text&quot;,
        '''  &quot;Default Tex [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property en() As String
            Get
                Return ResourceManager.GetString("en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;New Update Available! &quot;: &quot;Nouvelle Mise à Jour Disponible! &quot;,
        '''  &quot;Open .pgf&quot;: &quot;Ouvrir .pgf&quot;,
        '''  &quot;Custom&quot;: &quot;Personnaliser&quot;,
        '''  &quot;Game Compatibility&quot;: &quot;Compatibilité du Jeu&quot;,
        '''  &quot;Black&quot;: &quot;Noir&quot;,
        '''  &quot;White&quot;: &quot;Blanc&quot;,
        '''  &quot;Date Limit&quot;: &quot;Date Limite&quot;,
        '''  &quot;Start&quot;: &quot;Début&quot;,
        '''  &quot;End&quot;: &quot;Fin&quot;,
        '''  &quot;Auto Max Limit&quot;: &quot;Auto Max Limite&quot;,
        '''  &quot;Region&quot;: &quot;Région&quot;,
        '''  &quot;ROM Details&quot;: &quot;Détails du ROM&quot;,
        '''  &quot;File Name&quot;: &quot;Nom du Fichier&quot;,
        '''  &quot;Header&quot;: &quot;En-Tête&quot;,
        '''  &quot;Code&quot;: &quot;Code&quot;,
        '''  &quot;Description&quot;: &quot;Description&quot;,
        '''  &quot;Clear Text [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property fr() As String
            Get
                Return ResourceManager.GetString("fr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ndstool() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ndstool", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // amount of wonder cards (1-12)
        '''.definelabel amount,1
        '''
        '''// distance between names (pixels)
        '''.definelabel dist,12
        '''
        '''// status text color
        '''.definelabel test,0x7FFF
        '''
        '''// menu text color
        '''.definelabel menu,0x7FFF
        '''
        '''// selected text color
        '''.definelabel select,0x001F
        '''
        '''// text mode: 0=left, 1=center, 2=right
        '''.definelabel mode,1
        '''
        '''// menu text x-position (pixels)
        '''.definelabel mxpos,128
        '''
        '''// menu text y-position (pixels)
        '''.definelabel mypos,0
        '''
        '''// x-position for status text 1 (pixels)
        '''.definelabel d1xp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property options() As String
            Get
                Return ResourceManager.GetString("options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ppdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ppdbs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ppdbs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokémon Duodecuple Distribution
        '''by Prof. 9
        '''Version v1.4.1 &quot;Skinless&quot;
        '''
        '''Features:
        '''- Multiple Wonder Cards in a single distro ROM
        '''- Ignores date restrictions
        '''- Automatically fixes Wonder Card checksums
        '''
        '''How to generate a 12-distro ROM:
        '''1. Put a clean Liberty Ticket distro ROM in the tools folder, name it ticket.nds
        '''2. In the tools folder, edit options.asm to fit your needs (optional)
        '''3. Fire up 12distro.bat and use option 1 to create a base 12-distro ROM
        '''4. Extract Wonder Cards from other distro R [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property readme() As String
            Get
                Return ResourceManager.GetString("readme", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
